### ISSUE TITLE
`with_note()` signature change in v0.13 breaks calls with `&str` arguments

### ISSUE THREAD

**Issue by MellKam** [brendanzab/codespan#406]
After updating to version 0.13, I started receiving compilation errors in calls to with_note() where I passed a &str argument. This code worked correctly in v0.12, but with the new function signature using &impl ToString, it now fails to compile. Is this expected behavior?

```rs
Diagnostic::error()
    .with_code(Self::CODE)
    .with_message("type annotation required")
    .with_label(Label::primary(self.file_id, self.left))
    .with_label(Label::primary(self.file_id, self.right))
    .with_note("at least one side of the comparison must have a known type")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
ERROR: the size for values of type `str` cannot be known at compilation time
the trait `Sized` is not implemented for `str`
- required by an implicit `Sized` bound in `Diagnostic::<FileId>::with_note`
```
